title: "Faiçal AMMISAID"
description: "AI & Big Data Engineer | Certified Azure & Databricks"
baseurl: "" 
url: "https://faical.github.io"

theme: jekyll-theme-cayman

author:
  name: "Faiçal AMMISAID"
  email: "faical.outlook@outlook.com"

social_links:
  github: "https://github.com/AMMISAIDFaical"
  linkedin: "https://www.linkedin.com/in/faical-ammi-said-1009761b9/"

markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag
